typography_spectrum: 0.8111986194271594
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9620461466256529
  lightness: 0.7346477110404521
  saturation: 0.7228970904834569
  rhythmicContrast: 0.8210435167420655
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8978731378447264
analytics:
  google: null
  facebook: null
  twitter: null
name: Hell's Choice
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Art & Design International
    url: 'http://artanddesign.co.kr/'
    type: external
  - name: Swagger
    url: 'http://swagger.kr/'
    type: external
favicon: null
purpose: []
